-- Update in-run intro copy (ASCII-only, paste-safe). jsonb_set on documents.body_json; no run data touched.
begin;
update documents set body_json =
  jsonb_set(jsonb_set(body_json, '{INTRO,setup}', $j$"Each time a big decision lands, you'll hear the people around you out, then write your call in your own words and send it. Decide early and the story jumps ahead; wait too long and the handover drifts while you sit on it. <b>The real test:</b> can you hand over the whole truth and the whole job - and make yourself genuinely unnecessary - when everything that made you great pulls the other way?"$j$::jsonb),
           '{INTRO,paras}', $j$["This isn't a script. The year plays out in real time over four turning points, and the people around the handover bring you what they know as the days pass. You can wait for them - or reach out to any of them, Maya included, anytime, and ask. Some of them are holding the thing you most need to face.","Ashford is you. Every big customer relationship, every hard-won process, every instinct about what the company will and won't do lives in your head, and people have relied on that for a quarter-century. Maya is capable and ready - but the company has never known anyone else in the chair."]$j$::jsonb)
  where scenario_id = '7baa9166-cf5a-5836-89be-c401730fbc1d' and key = 'solo_content';  -- handover
update documents set body_json =
  jsonb_set(jsonb_set(body_json, '{INTRO,setup}', $j$"Each time a decision lands, you'll hear your team out, then write your call in your own words and send it. Decide early and time jumps ahead; wait too long and the fleet keeps rolling on fumes while you deliberate. <b>The real test:</b> can you protect what makes Cardinal great without letting it get someone killed - before a cost nobody's tracking catches up with you?"$j$::jsonb),
           '{INTRO,paras}', $j$["This is not a script. The crisis runs in real time across four decision windows, and your team brings you what they know as the days pass. You can wait for them - or reach out to any of them, any time, and ask. Some of them are sitting on the thing you most need to see.","Cardinal is built on one sacred promise: <b>we always deliver.</b> Blizzard, breakdown, 3 a.m. - the fuel gets there. But to always deliver, drivers run past their hours and logs get \"adjusted.\" Everyone knows; no one says it; the trucks keep rolling."]$j$::jsonb)
  where scenario_id = '6fb47119-8374-588e-baad-a403519b0bce' and key = 'solo_content';  -- overdrive
update documents set body_json =
  jsonb_set(jsonb_set(body_json, '{INTRO,setup}', $j$"By morning, everyone's looking to you for a plan. Over the coming weeks you'll weigh routes, jobs, and cash against the trust of the people who fly and fix these planes. You'll be judged on two things - whether Halcyon comes through the shock, and how you led people through it. And how openly your team levels with you depends on the trust you'd built before it hit."$j$::jsonb),
           '{INTRO,paras}', $j$["This is not a script. The week runs in real time, and your team brings you what they know across the days. You can wait for them - or reach out to any of them, any time, and ask.","Each week you'll hear your team out, then write the call in your own words and send it. Decide early and time jumps ahead. Let the week run out and the world moves without you."]$j$::jsonb)
  where scenario_id = '7ab2e6fc-b8fe-5c93-9084-22c2907ae915' and key = 'solo_content';  -- shockwave
update documents set body_json =
  jsonb_set(jsonb_set(body_json, '{INTRO,setup}', $j$"Each month, you'll hear your team out, then write your call in your own words and send it. Decide early and time jumps ahead; wait too long and the squeeze tightens while you sit on it. <b>The real test:</b> under real scarcity, do you spread the pain fairly and tell the truth - or protect the top and yourself while the floor pays? Scarcity is where a company finds out who it really protects."$j$::jsonb),
           '{INTRO,paras}', $j$["This is not a script. The crisis runs in real time across four months, and your team brings you what they know as the days pass. You can wait for them - or reach out to any of them, any time, and ask. Some of them are holding the thing you most need to hear.","Delph isn't dying - but the margin that kept everyone employed has evaporated. The cash that used to feel comfortable now has a number of months attached to it, and every month you decide who absorbs the pain."]$j$::jsonb)
  where scenario_id = 'eaf60170-9529-52c0-af8f-eaed27b16fd4' and key = 'solo_content';  -- squeeze
commit;
